# This is file is used to help customize PyGrinder documentation building process on ReadTheDocs.

version: 2

formats:
  - htmlzip
  - pdf
  - epub

sphinx:
   configuration: docs/conf.py
   fail_on_warning: false

build:
   os: ubuntu-22.04

   tools:
      python: "3.10"
